### PR TITLE
Add script to download original images and video

### LINKED ISSUE #16: Feature request: Download full-size images from Twitter
@masukomi points out in #13 that the images in the Twitter archive are not the original size.

Example: an image in my archive is 600x809. If I download from Twitter appending `?format=jpg&name=large` then it gives me an image that is 780x1052.

Conceivably we could automate the downloading of full size images.

### PR DESCRIPTION
**Pull request by timhutton**
Changed `parser.py` to avoid overwriting media if it already exists, in case you need to run it again after downloading images.

This closes #16

### CODE REVIEW

**Comment by timhutton** [comment]
If anyone can try this out before I merge that would be useful.

@masukomi @cooljeanius @rossgrady @davidstosik @alexjc

**Comment by cooljeanius** [comment]
Starting it now; might take awhile as it's got 7090 images to go through...

**Comment by timhutton** [comment]
Mine took 17mins:

```
H:\Tim\twitter_archive_2022-04-28>c:\Python36-32\python.exe ..\twitter-archive-parser\download_better_images.py

This script will attempt to download 349 files from twimg.com. If the downloaded version is larger
than the version in media/ then it will be overwritten. Please be aware that this script may download
a lot of data, which will cost you money if you are paying for bandwidth. Please be aware that
the servers might block these requests if they are too frequent.

OK to continue? [y/n]y
1/349: Fail. Downloaded version is same size or smaller than media\1008410063189565440-Df6XLPIXcAIOl6J.jpg, 1.6MB downloaded.
2/349: Fail. Downloaded version is same size or smaller than media\1010638114417766400-DgaB-pAW4AATrMb.jpg, 2.1MB downloaded.
...
321/349: Success. Overwrote media\959419782515838976-DVCLIpKX4AEpqeV.jpg with downloaded version that is 274% larger, 0.3MB downloaded.
322/349: Success. Overwrote media\960965302547861505-DVYIg2gXcAU0KTQ.jpg with downloaded version that is 958% larger, 1.4MB downloaded.
323/349: Success. Overwrote media\960998682878455808-DVYnL5rW0AAnDw-.jpg with downloaded version that is 82% larger, 0.1MB downloaded.
324/349: Success. Overwrote media\961271588669837312-DVcfBrUWkAAriP9.jpg with downloaded version that is 616% larger, 0.7MB downloaded.
325/349: Fail. Downloaded version is same size or smaller than media\961278933600817152-DVcmD5WW4AAREFi.jpg, 0.1MB downloaded.
326/349: Success. Overwrote media\965585804302192642-DWZyIctXkAAqEDO.jpg with downloaded version that is 324% larger, 0.1MB downloaded.
327/349: Fail. Downloaded version is same size or smaller than media\965714939850776576-DWboXn9W0AAL52q.jpg, 0.1MB downloaded.
328/349: Fail. Downloaded version is same size or smaller than media\971504708136382465-DXt46L9X0AE2puI.mp4, 0.1MB downloaded.
329/349: Fail. Media couldn't be retrieved: https://video.twimg.com/tweet_video/Jz48B42RWFaNE3Mq.mp4 Filename: media\972110412794785792-Jz48B42RWFaNE3Mq.mp4
330/349: Fail. Media couldn't be retrieved: https://video.twimg.com/tweet_video/M0XPz5t-GfYjW--P.mp4 Filename: media\972110428519174144-M0XPz5t-GfYjW--P.mp4
331/349: Fail. Downloaded version is same size or smaller than media\973585403679838208-DYLdl3iWAAANyxI.jpg, 0.2MB downloaded.
332/349: Success. Overwrote media\973672374213251072-DYD2JzYU8AAAQTj.jpg with downloaded version that is 40% larger, 0.1MB downloaded.
333/349: Fail. Downloaded version is same size or smaller than media\973894378346475520-DYPseebX0AAoIlu.jpg, 0.0MB downloaded.
334/349: Fail. Downloaded version is same size or smaller than media\975136768004710400-DYhhYiQW0AAU1ot.mp4, 1.6MB downloaded.
335/349: Success. Overwrote media\975138957523595267-DYhjNZ7WAAA3v9w.jpg with downloaded version that is 585% larger, 0.8MB downloaded.
336/349: Fail. Downloaded version is same size or smaller than media\975831768099147778-DYrZKf4X0AIj8qQ.jpg, 0.0MB downloaded.
337/349: Fail. Downloaded version is same size or smaller than media\976145702958092288-DYv3GJsXcAAsbzG.mp4, 2.3MB downloaded.
338/349: Fail. Downloaded version is same size or smaller than media\978603550161989633-DZSwv-TWsAAcwPe.jpg, 0.1MB downloaded.
339/349: Fail. Downloaded version is same size or smaller than media\979472788615557120-DZfI8MeX0AEYmuP.mp4, 1.3MB downloaded.
340/349: Fail. Downloaded version is same size or smaller than media\980104791329296385-DZoIG2jW4AA40cD.jpg, 0.2MB downloaded.
341/349: Fail. Downloaded version is same size or smaller than media\981531637413539840-DZ8Z0VLVAAExzfe.jpg, 0.0MB downloaded.
342/349: Success. Overwrote media\981611082744778753-DZ9h880XkAAhzga.jpg with downloaded version that is 1006% larger, 1.7MB downloaded.
343/349: Success. Overwrote media\986738901472694277-DbGZPYLX4AEmGLa.jpg with downloaded version that is 25% larger, 0.1MB downloaded.
344/349: Success. Overwrote media\988456740206374912-DbeyzQdWAAAlvnR.jpg with downloaded version that is 747% larger, 1.8MB downloaded.
345/349: Fail. Downloaded version is same size or smaller than media\990344350184943616-Db5oybkWkAIJt7c.mp4, 14.1MB downloaded.
346/349: Success. Overwrote media\994144330846752769-Db9dqPuXUAEPaNQ.jpg with downloaded version that is 113% larger, 0.9MB downloaded.
347/349: Fail. Downloaded version is same size or smaller than media\995672648830144512-DdFW_nuXkAI-4LK.jpg, 0.0MB downloaded.
348/349: Success. Overwrote media\998218105020211200-Ddlao5BW0AUpR2Q.jpg with downloaded version that is 106% larger, 0.1MB downloaded.
349/349: Success. Overwrote media\998290563861549057-Ddqj9bzUQAEuRu3.jpg with downloaded version that is 125% larger, 0.6MB downloaded.

Replaced 156 media files with larger versions.
Total downloaded: 177.3MB = 0.17GB
Time taken: 1003s
```

Looks like none of the videos were available at a larger size. Quite a few videos aren't available on the servers, I'm not sure why.

Lots of larger images were found. Around half of the archived media were upgraded.

**Comment by twoscomplement** [comment]
I just started a run - seems to be working smoothly.

A couple of thoughts:
- Maybe a different word than "Fail." when reporting an image that is not available at a higher resolution? (Caught me wondering if something was wrong with my network)
- Given how long it can take for a full run, I wonder if there's some value in having the script track progress (write an index to a file after each successful attempt?) allowing restarts?

**Comment by timhutton** [comment]
@twoscomplement Will change the wording.

Ideally it would check for the size before downloading, then restarts wouldn't be a problem. I haven't found a way yet - please let me know if you find one that works. I looked at:
- making HEAD requests - twing.com rejects them it seems
- using `requests` in [stream mode](https://stackoverflow.com/questions/14270698/get-file-size-using-python-requests-while-only-getting-the-header/44299915#44299915) - but that requires a pip install. Maybe that's not too bad, since it doesn't affect parser.py.

**Comment by twoscomplement** [comment]
Suggestion: print (or write a log file) of files for which there were errors - I had at least one.

(In my case, there's an image URL in my tweets.js that appears invalid: it gives a 404. The tweet it's referenced from exists, but has a different image URL. The file name that 404s is present in my archive's media directory.)

**Comment by twoscomplement** [comment]
Regarding restarts, I figure that anything that can prevent the need for potentially large-scale interactions with twitter's servers is probably advantageous :slightly_smiling_face:

**Comment by cooljeanius** [comment]
> I just started a run - seems to be working smoothly.
> 
> A couple of thoughts:
> 
>     * Maybe a different word than "Fail." when reporting an image that is not available at a higher resolution? (Caught me wondering if something was wrong with my network)
> 

Yeah I think "Skipped." would make more sense?

>     * Given how long it can take for a full run, I wonder if there's some value in having the script track progress (write an index to a file after each successful attempt?) allowing restarts?

Well the [current number]/[total number] kind of counts as a way of tracking progress; I'm at 3377/7050 currently after 3-ish hours... and I agree a logfile would be nice; like, I could have piped the output through `tee` if I'd realized I might have wanted to, but I'd have to restart the thing to do that now...

**Comment by timhutton** [comment]
Code now:
- Installs `requests` if not installed and user agrees.
- Avoids downloading content unless the size is larger than the existing file. This should save a lot of bandwidth and makes restarting less painful.
- Logs errors to file
- Says 'Skipped' when the available version is same size or smaller.

**Comment by cooljeanius** [comment]
So, the script finished up running after I went to sleep last night:
```
Replaced 4628 media files with larger versions.
Total downloaded: 1909.7MB = 1.86GB
Time taken: 19079s
```
Would the full output be useful at all, or is this pretty much done now?

**Comment by timhutton** [comment]
Wow. 6 hours. I'm glad you were able to get hold of your data.

At some point I'd like to understand what happened with the failed media, so maybe hang onto your logs - I have plenty of cases in my own archive to be going on with for now.

**Comment by timhutton** [comment]
If you want to give the new script a go it would be a useful check. It should just report 'skipped' for most items.

**Comment by rossgrady** [comment]
Coming to this late, but I'm running now & thus far it seems like a lot of .mp4 files aren't fetchable. But a few have been (huh), although they were all same size as the one in the archive anyway.

Do we know for sure whether Twitter compressed/downscaled videos on upload but stored the originals, as with images?

**Comment by timhutton** [comment]
@rossgrady I'm trying to debug the fails and see if we can get better quality ones. An example JSON for a tweet with a video looks like this:

```
    "tweet" : {
      "retweeted" : false,
      "source" : "<a href=\"https://mobile.twitter.com\" rel=\"nofollow\">Twitter Web App</a>",
      "entities" : {
        "user_mentions" : [
          {
            "name" : "David Chaney",
            "screen_name" : "chaoticmass",
            "indices" : [
              "0",
              "12"
            ],
            "id_str" : "34676511",
            "id" : "34676511"
          },
          {
            "name" : "Seth Lombardy",
            "screen_name" : "sethllombardy",
            "indices" : [
              "13",
              "27"
            ],
            "id_str" : "1340012104837840896",
            "id" : "1340012104837840896"
          }
        ],
        "urls" : [
          {
            "url" : "https://t.co/XCoUjiVotX",
            "expanded_url" : "https://timhutton.github.io/mobius-transforms/dfs_recipes.html",
            "display_url" : "timhutton.github.io/mobius-transfo…",
            "indices" : [
              "82",
              "105"
            ]
          }
        ],
        "symbols" : [ ],
        "media" : [
          {
            "expanded_url" : "https://twitter.com/_tim_hutton_/status/1493679723985178625/video/1",
            "indices" : [
              "106",
              "129"
            ],
            "url" : "https://t.co/SG3FtFVyns",
            "media_url" : "http://pbs.twimg.com/ext_tw_video_thumb/1493678749400944655/pu/img/Yp_ThQ_CLafFBcLS.jpg",
            "id_str" : "1493678749400944655",
            "id" : "1493678749400944655",
            "media_url_https" : "https://pbs.twimg.com/ext_tw_video_thumb/1493678749400944655/pu/img/Yp_ThQ_CLafFBcLS.jpg",
            "sizes" : {
              "thumb" : {
                "w" : "150",
                "h" : "150",
                "resize" : "crop"
              },
              "medium" : {
                "w" : "1200",
                "h" : "587",
                "resize" : "fit"
              },
              "small" : {
                "w" : "680",
                "h" : "333",
                "resize" : "fit"
              },
              "large" : {
                "w" : "1880",
                "h" : "920",
                "resize" : "fit"
              }
            },
            "type" : "photo",
            "display_url" : "pic.twitter.com/SG3FtFVyns"
          }
        ],
        "hashtags" : [ ]
      },
      "display_text_range" : [
        "0",
        "129"
      ],
      "favorite_count" : "2",
      "in_reply_to_status_id_str" : "1491490690978791430",
      "id_str" : "1493679723985178625",
      "in_reply_to_user_id" : "2246902119",
      "truncated" : false,
      "retweet_count" : "1",
      "id" : "1493679723985178625",
      "in_reply_to_status_id" : "1491490690978791430",
      "possibly_sensitive" : false,
      "created_at" : "Tue Feb 15 20:12:52 +0000 2022",
      "favorited" : false,
      "full_text" : "@chaoticmass @sethllombardy Sliders are now live. Please let me know of any bugs.\nhttps://t.co/XCoUjiVotX https://t.co/SG3FtFVyns",
      "lang" : "en",
      "in_reply_to_screen_name" : "_tim_hutton_",
      "in_reply_to_user_id_str" : "2246902119",
      "extended_entities" : {
        "media" : [
          {
            "expanded_url" : "https://twitter.com/_tim_hutton_/status/1493679723985178625/video/1",
            "indices" : [
              "106",
              "129"
            ],
            "url" : "https://t.co/SG3FtFVyns",
            "media_url" : "http://pbs.twimg.com/ext_tw_video_thumb/1493678749400944655/pu/img/Yp_ThQ_CLafFBcLS.jpg",
            "id_str" : "1493678749400944655",
            "video_info" : {
              "aspect_ratio" : [
                "47",
                "23"
              ],
              "duration_millis" : "30966",
              "variants" : [
                {
                  "bitrate" : "256000",
                  "content_type" : "video/mp4",
                  "url" : "https://video.twimg.com/ext_tw_video/1493678749400944655/pu/vid/550x270/2HJfZEO-rkLt02vO.mp4?tag=12"
                },
                {
                  "bitrate" : "832000",
                  "content_type" : "video/mp4",
                  "url" : "https://video.twimg.com/ext_tw_video/1493678749400944655/pu/vid/734x360/8ozH3FpjGnHvZYnU.mp4?tag=12"
                },
                {
                  "content_type" : "application/x-mpegURL",
                  "url" : "https://video.twimg.com/ext_tw_video/1493678749400944655/pu/pl/KuttNZoJYYzJIHf4.m3u8?tag=12&container=fmp4"
                },
                {
                  "bitrate" : "2176000",
                  "content_type" : "video/mp4",
                  "url" : "https://video.twimg.com/ext_tw_video/1493678749400944655/pu/vid/1470x720/iuSYsk2rbOuR91tU.mp4?tag=12"
                }
              ]
            },
            "additional_media_info" : {
              "monetizable" : false
            },
            "id" : "1493678749400944655",
            "media_url_https" : "https://pbs.twimg.com/ext_tw_video_thumb/1493678749400944655/pu/img/Yp_ThQ_CLafFBcLS.jpg",
            "sizes" : {
              "thumb" : {
                "w" : "150",
                "h" : "150",
                "resize" : "crop"
              },
              "medium" : {
                "w" : "1200",
                "h" : "587",
                "resize" : "fit"
              },
              "small" : {
                "w" : "680",
                "h" : "333",
                "resize" : "fit"
              },
              "large" : {
                "w" : "1880",
                "h" : "920",
                "resize" : "fit"
              }
            },
            "type" : "video",
            "display_url" : "pic.twitter.com/SG3FtFVyns"
          }
        ]
      }
    }
```

It looks like they store variants at different bitrates. For this video the filename is `1493679723985178625-iuSYsk2rbOuR91tU.mp4`. The script attempts to download from `https://video.twimg.com/tweet_video/iuSYsk2rbOuR91tU.mp4` and fails.

**Comment by rossgrady** [comment]
Datapoint, just for fun. This is with the version that resulted from the initial merge of this PR -- I started running it & even though you dug in & figured out the video situation, I went ahead & left it running because at least I'd get the still images done. 

```
Replaced 3956 of 10845 media files with larger versions.
Total downloaded: 1821.5MB = 1.78GB
Time taken: 15314s
Wrote log to download_log.txt
python3 download_better_images.py  244.98s user 47.55s system 1% cpu 4:15:16.46 total
```

**Comment by twoscomplement** [comment]
> (In my case, there's an image URL in my tweets.js that appears invalid: it gives a 404. The tweet it's referenced from exists, but has a different image URL. The file name that 404s is present in my archive's media directory.)

For the record, the 404 happened to be an image in a retweet of a tweet from a protected account.

**Pull request merged**
