### PR TITLE
Add a .gitignore file to ignore the twitter archive files

### PR DESCRIPTION
**Pull request by miniupnp**

### CODE REVIEW

**Review by timhutton — COMMENTED** [review]
Best practice for git users:
e.g. `python ../<git folder>/parser.py`

Avoids the need for this file.

**Comment by miniupnp** [comment]
> Best practice for git users: e.g. `python ../<git folder>/parser.py`
> 
> Avoids the need for this file.

I agree it is not needed. It doesn't do harm. And it might be useful for at least some developers ;)

**Comment by timhutton** [comment]
Rejecting this because I want as few files as possible in the repo. I hope that's OK?

**Comment by miniupnp** [comment]
> Rejecting this because I want as few files as possible in the repo. I hope that's OK?
of course, that's your repo !

however a .gitignore file is pretty standard in a git repo.

**Pull request closed without merging**
